// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestauditlog"
)

// RequestAuditLogCreate is the builder for creating a RequestAuditLog entity.
type RequestAuditLogCreate struct {
	config
	mutation *RequestAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *RequestAuditLogCreate) SetRequestID(v string) *RequestAuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableRequestID(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RequestAuditLogCreate) SetUserID(v int64) *RequestAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RequestAuditLogCreate) SetAPIKeyID(v int64) *RequestAuditLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *RequestAuditLogCreate) SetAccountID(v int64) *RequestAuditLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableAccountID(v *int64) *RequestAuditLogCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RequestAuditLogCreate) SetGroupID(v int64) *RequestAuditLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableGroupID(v *int64) *RequestAuditLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RequestAuditLogCreate) SetPlatform(v string) *RequestAuditLogCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *RequestAuditLogCreate) SetEndpoint(v string) *RequestAuditLogCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableEndpoint(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *RequestAuditLogCreate) SetModel(v string) *RequestAuditLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableModel(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *RequestAuditLogCreate) SetStream(v bool) *RequestAuditLogCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableStream(v *bool) *RequestAuditLogCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *RequestAuditLogCreate) SetStatusCode(v int) *RequestAuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableStatusCode(v *int) *RequestAuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestAuditLogCreate) SetDurationMs(v int) *RequestAuditLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableDurationMs(v *int) *RequestAuditLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestAuditLogCreate) SetRequestBody(v string) *RequestAuditLogCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableRequestBody(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestAuditLogCreate) SetResponseBody(v string) *RequestAuditLogCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableResponseBody(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_c *RequestAuditLogCreate) SetRequestBodyTruncated(v bool) *RequestAuditLogCreate {
	_c.mutation.SetRequestBodyTruncated(v)
	return _c
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableRequestBodyTruncated(v *bool) *RequestAuditLogCreate {
	if v != nil {
		_c.SetRequestBodyTruncated(*v)
	}
	return _c
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_c *RequestAuditLogCreate) SetResponseBodyTruncated(v bool) *RequestAuditLogCreate {
	_c.mutation.SetResponseBodyTruncated(v)
	return _c
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableResponseBodyTruncated(v *bool) *RequestAuditLogCreate {
	if v != nil {
		_c.SetResponseBodyTruncated(*v)
	}
	return _c
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_c *RequestAuditLogCreate) SetRequestBodyBytes(v int) *RequestAuditLogCreate {
	_c.mutation.SetRequestBodyBytes(v)
	return _c
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableRequestBodyBytes(v *int) *RequestAuditLogCreate {
	if v != nil {
		_c.SetRequestBodyBytes(*v)
	}
	return _c
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_c *RequestAuditLogCreate) SetResponseBodyBytes(v int) *RequestAuditLogCreate {
	_c.mutation.SetResponseBodyBytes(v)
	return _c
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableResponseBodyBytes(v *int) *RequestAuditLogCreate {
	if v != nil {
		_c.SetResponseBodyBytes(*v)
	}
	return _c
}

// SetIsMocked sets the "is_mocked" field.
func (_c *RequestAuditLogCreate) SetIsMocked(v bool) *RequestAuditLogCreate {
	_c.mutation.SetIsMocked(v)
	return _c
}

// SetNillableIsMocked sets the "is_mocked" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableIsMocked(v *bool) *RequestAuditLogCreate {
	if v != nil {
		_c.SetIsMocked(*v)
	}
	return _c
}

// SetMockRuleID sets the "mock_rule_id" field.
func (_c *RequestAuditLogCreate) SetMockRuleID(v int64) *RequestAuditLogCreate {
	_c.mutation.SetMockRuleID(v)
	return _c
}

// SetNillableMockRuleID sets the "mock_rule_id" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableMockRuleID(v *int64) *RequestAuditLogCreate {
	if v != nil {
		_c.SetMockRuleID(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestAuditLogCreate) SetErrorMessage(v string) *RequestAuditLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableErrorMessage(v *string) *RequestAuditLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestAuditLogCreate) SetCreatedAt(v time.Time) *RequestAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestAuditLogCreate) SetNillableCreatedAt(v *time.Time) *RequestAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RequestAuditLogMutation object of the builder.
func (_c *RequestAuditLogCreate) Mutation() *RequestAuditLogMutation {
	return _c.mutation
}

// Save creates the RequestAuditLog in the database.
func (_c *RequestAuditLogCreate) Save(ctx context.Context) (*RequestAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestAuditLogCreate) SaveX(ctx context.Context) *RequestAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestAuditLogCreate) defaults() {
	if _, ok := _c.mutation.Stream(); !ok {
		v := requestauditlog.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.RequestBodyTruncated(); !ok {
		v := requestauditlog.DefaultRequestBodyTruncated
		_c.mutation.SetRequestBodyTruncated(v)
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		v := requestauditlog.DefaultResponseBodyTruncated
		_c.mutation.SetResponseBodyTruncated(v)
	}
	if _, ok := _c.mutation.RequestBodyBytes(); !ok {
		v := requestauditlog.DefaultRequestBodyBytes
		_c.mutation.SetRequestBodyBytes(v)
	}
	if _, ok := _c.mutation.ResponseBodyBytes(); !ok {
		v := requestauditlog.DefaultResponseBodyBytes
		_c.mutation.SetResponseBodyBytes(v)
	}
	if _, ok := _c.mutation.IsMocked(); !ok {
		v := requestauditlog.DefaultIsMocked
		_c.mutation.SetIsMocked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestAuditLogCreate) check() error {
	if v, ok := _c.mutation.RequestID(); ok {
		if err := requestauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RequestAuditLog.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "RequestAuditLog.api_key_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RequestAuditLog.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := requestauditlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.platform": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := requestauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := requestauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "RequestAuditLog.stream"`)}
	}
	if _, ok := _c.mutation.RequestBodyTruncated(); !ok {
		return &ValidationError{Name: "request_body_truncated", err: errors.New(`ent: missing required field "RequestAuditLog.request_body_truncated"`)}
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		return &ValidationError{Name: "response_body_truncated", err: errors.New(`ent: missing required field "RequestAuditLog.response_body_truncated"`)}
	}
	if _, ok := _c.mutation.RequestBodyBytes(); !ok {
		return &ValidationError{Name: "request_body_bytes", err: errors.New(`ent: missing required field "RequestAuditLog.request_body_bytes"`)}
	}
	if _, ok := _c.mutation.ResponseBodyBytes(); !ok {
		return &ValidationError{Name: "response_body_bytes", err: errors.New(`ent: missing required field "RequestAuditLog.response_body_bytes"`)}
	}
	if _, ok := _c.mutation.IsMocked(); !ok {
		return &ValidationError{Name: "is_mocked", err: errors.New(`ent: missing required field "RequestAuditLog.is_mocked"`)}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := requestauditlog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestAuditLog.created_at"`)}
	}
	return nil
}

func (_c *RequestAuditLogCreate) sqlSave(ctx context.Context) (*RequestAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestAuditLogCreate) createSpec() (*RequestAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestauditlog.Table, sqlgraph.NewFieldSpec(requestauditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requestauditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(requestauditlog.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(requestauditlog.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(requestauditlog.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(requestauditlog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(requestauditlog.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(requestauditlog.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(requestauditlog.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(requestauditlog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(requestauditlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestauditlog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(requestauditlog.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = &value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(requestauditlog.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = &value
	}
	if value, ok := _c.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyTruncated, field.TypeBool, value)
		_node.RequestBodyTruncated = value
	}
	if value, ok := _c.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyTruncated, field.TypeBool, value)
		_node.ResponseBodyTruncated = value
	}
	if value, ok := _c.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyBytes, field.TypeInt, value)
		_node.RequestBodyBytes = value
	}
	if value, ok := _c.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyBytes, field.TypeInt, value)
		_node.ResponseBodyBytes = value
	}
	if value, ok := _c.mutation.IsMocked(); ok {
		_spec.SetField(requestauditlog.FieldIsMocked, field.TypeBool, value)
		_node.IsMocked = value
	}
	if value, ok := _c.mutation.MockRuleID(); ok {
		_spec.SetField(requestauditlog.FieldMockRuleID, field.TypeInt64, value)
		_node.MockRuleID = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestauditlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAuditLog.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *RequestAuditLogUpsertOne {
	_c.conflict = opts
	return &RequestAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditLogCreate) OnConflictColumns(columns ...string) *RequestAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// RequestAuditLogUpsertOne is the builder for "upsert"-ing
	//  one RequestAuditLog node.
	RequestAuditLogUpsertOne struct {
		create *RequestAuditLogCreate
	}

	// RequestAuditLogUpsert is the "OnConflict" setter.
	RequestAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *RequestAuditLogUpsert) SetRequestID(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateRequestID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestAuditLogUpsert) ClearRequestID() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestAuditLogUpsert) SetUserID(v int64) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateUserID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RequestAuditLogUpsert) AddUserID(v int64) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestAuditLogUpsert) SetAPIKeyID(v int64) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateAPIKeyID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestAuditLogUpsert) AddAPIKeyID(v int64) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldAPIKeyID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *RequestAuditLogUpsert) SetAccountID(v int64) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateAccountID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestAuditLogUpsert) AddAccountID(v int64) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestAuditLogUpsert) ClearAccountID() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldAccountID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RequestAuditLogUpsert) SetGroupID(v int64) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateGroupID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestAuditLogUpsert) AddGroupID(v int64) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestAuditLogUpsert) ClearGroupID() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldGroupID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RequestAuditLogUpsert) SetPlatform(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdatePlatform() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldPlatform)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestAuditLogUpsert) SetEndpoint(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateEndpoint() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldEndpoint)
	return u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *RequestAuditLogUpsert) ClearEndpoint() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldEndpoint)
	return u
}

// SetModel sets the "model" field.
func (u *RequestAuditLogUpsert) SetModel(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateModel() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *RequestAuditLogUpsert) ClearModel() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldModel)
	return u
}

// SetStream sets the "stream" field.
func (u *RequestAuditLogUpsert) SetStream(v bool) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateStream() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldStream)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *RequestAuditLogUpsert) SetStatusCode(v int) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateStatusCode() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestAuditLogUpsert) AddStatusCode(v int) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestAuditLogUpsert) ClearStatusCode() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldStatusCode)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestAuditLogUpsert) SetDurationMs(v int) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateDurationMs() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestAuditLogUpsert) AddDurationMs(v int) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestAuditLogUpsert) ClearDurationMs() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldDurationMs)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *RequestAuditLogUpsert) SetRequestBody(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateRequestBody() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldRequestBody)
	return u
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestAuditLogUpsert) ClearRequestBody() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldRequestBody)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *RequestAuditLogUpsert) SetResponseBody(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateResponseBody() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestAuditLogUpsert) ClearResponseBody() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldResponseBody)
	return u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestAuditLogUpsert) SetRequestBodyTruncated(v bool) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldRequestBodyTruncated, v)
	return u
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateRequestBodyTruncated() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldRequestBodyTruncated)
	return u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestAuditLogUpsert) SetResponseBodyTruncated(v bool) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldResponseBodyTruncated, v)
	return u
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateResponseBodyTruncated() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldResponseBodyTruncated)
	return u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestAuditLogUpsert) SetRequestBodyBytes(v int) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldRequestBodyBytes, v)
	return u
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateRequestBodyBytes() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldRequestBodyBytes)
	return u
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestAuditLogUpsert) AddRequestBodyBytes(v int) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldRequestBodyBytes, v)
	return u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestAuditLogUpsert) SetResponseBodyBytes(v int) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldResponseBodyBytes, v)
	return u
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateResponseBodyBytes() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldResponseBodyBytes)
	return u
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestAuditLogUpsert) AddResponseBodyBytes(v int) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldResponseBodyBytes, v)
	return u
}

// SetIsMocked sets the "is_mocked" field.
func (u *RequestAuditLogUpsert) SetIsMocked(v bool) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldIsMocked, v)
	return u
}

// UpdateIsMocked sets the "is_mocked" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateIsMocked() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldIsMocked)
	return u
}

// SetMockRuleID sets the "mock_rule_id" field.
func (u *RequestAuditLogUpsert) SetMockRuleID(v int64) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldMockRuleID, v)
	return u
}

// UpdateMockRuleID sets the "mock_rule_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateMockRuleID() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldMockRuleID)
	return u
}

// AddMockRuleID adds v to the "mock_rule_id" field.
func (u *RequestAuditLogUpsert) AddMockRuleID(v int64) *RequestAuditLogUpsert {
	u.Add(requestauditlog.FieldMockRuleID, v)
	return u
}

// ClearMockRuleID clears the value of the "mock_rule_id" field.
func (u *RequestAuditLogUpsert) ClearMockRuleID() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldMockRuleID)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestAuditLogUpsert) SetErrorMessage(v string) *RequestAuditLogUpsert {
	u.Set(requestauditlog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestAuditLogUpsert) UpdateErrorMessage() *RequestAuditLogUpsert {
	u.SetExcluded(requestauditlog.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestAuditLogUpsert) ClearErrorMessage() *RequestAuditLogUpsert {
	u.SetNull(requestauditlog.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditLogUpsertOne) UpdateNewValues() *RequestAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestauditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestAuditLogUpsertOne) Ignore() *RequestAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditLogUpsertOne) DoNothing() *RequestAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditLogCreate.OnConflict
// documentation for more info.
func (u *RequestAuditLogUpsertOne) Update(set func(*RequestAuditLogUpsert)) *RequestAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestAuditLogUpsertOne) SetRequestID(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateRequestID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestAuditLogUpsertOne) ClearRequestID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestAuditLogUpsertOne) SetUserID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RequestAuditLogUpsertOne) AddUserID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateUserID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestAuditLogUpsertOne) SetAPIKeyID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestAuditLogUpsertOne) AddAPIKeyID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateAPIKeyID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestAuditLogUpsertOne) SetAccountID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestAuditLogUpsertOne) AddAccountID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateAccountID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestAuditLogUpsertOne) ClearAccountID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestAuditLogUpsertOne) SetGroupID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestAuditLogUpsertOne) AddGroupID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateGroupID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestAuditLogUpsertOne) ClearGroupID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *RequestAuditLogUpsertOne) SetPlatform(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdatePlatform() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdatePlatform()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestAuditLogUpsertOne) SetEndpoint(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateEndpoint() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *RequestAuditLogUpsertOne) ClearEndpoint() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *RequestAuditLogUpsertOne) SetModel(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateModel() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *RequestAuditLogUpsertOne) ClearModel() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearModel()
	})
}

// SetStream sets the "stream" field.
func (u *RequestAuditLogUpsertOne) SetStream(v bool) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateStream() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestAuditLogUpsertOne) SetStatusCode(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestAuditLogUpsertOne) AddStatusCode(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateStatusCode() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestAuditLogUpsertOne) ClearStatusCode() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestAuditLogUpsertOne) SetDurationMs(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestAuditLogUpsertOne) AddDurationMs(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateDurationMs() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestAuditLogUpsertOne) ClearDurationMs() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestAuditLogUpsertOne) SetRequestBody(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateRequestBody() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestAuditLogUpsertOne) ClearRequestBody() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearRequestBody()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestAuditLogUpsertOne) SetResponseBody(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateResponseBody() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestAuditLogUpsertOne) ClearResponseBody() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearResponseBody()
	})
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestAuditLogUpsertOne) SetRequestBodyTruncated(v bool) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBodyTruncated(v)
	})
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateRequestBodyTruncated() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBodyTruncated()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestAuditLogUpsertOne) SetResponseBodyTruncated(v bool) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateResponseBodyTruncated() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestAuditLogUpsertOne) SetRequestBodyBytes(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBodyBytes(v)
	})
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestAuditLogUpsertOne) AddRequestBodyBytes(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddRequestBodyBytes(v)
	})
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateRequestBodyBytes() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBodyBytes()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestAuditLogUpsertOne) SetResponseBodyBytes(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestAuditLogUpsertOne) AddResponseBodyBytes(v int) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateResponseBodyBytes() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// SetIsMocked sets the "is_mocked" field.
func (u *RequestAuditLogUpsertOne) SetIsMocked(v bool) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetIsMocked(v)
	})
}

// UpdateIsMocked sets the "is_mocked" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateIsMocked() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateIsMocked()
	})
}

// SetMockRuleID sets the "mock_rule_id" field.
func (u *RequestAuditLogUpsertOne) SetMockRuleID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetMockRuleID(v)
	})
}

// AddMockRuleID adds v to the "mock_rule_id" field.
func (u *RequestAuditLogUpsertOne) AddMockRuleID(v int64) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddMockRuleID(v)
	})
}

// UpdateMockRuleID sets the "mock_rule_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateMockRuleID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateMockRuleID()
	})
}

// ClearMockRuleID clears the value of the "mock_rule_id" field.
func (u *RequestAuditLogUpsertOne) ClearMockRuleID() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearMockRuleID()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestAuditLogUpsertOne) SetErrorMessage(v string) *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestAuditLogUpsertOne) UpdateErrorMessage() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestAuditLogUpsertOne) ClearErrorMessage() *RequestAuditLogUpsertOne {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *RequestAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestAuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestAuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestAuditLogCreateBulk is the builder for creating many RequestAuditLog entities in bulk.
type RequestAuditLogCreateBulk struct {
	config
	err      error
	builders []*RequestAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestAuditLog entities in the database.
func (_c *RequestAuditLogCreateBulk) Save(ctx context.Context) ([]*RequestAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestAuditLogCreateBulk) SaveX(ctx context.Context) []*RequestAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestAuditLogUpsertBulk {
	_c.conflict = opts
	return &RequestAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditLogCreateBulk) OnConflictColumns(columns ...string) *RequestAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditLogUpsertBulk{
		create: _c,
	}
}

// RequestAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestAuditLog nodes.
type RequestAuditLogUpsertBulk struct {
	create *RequestAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditLogUpsertBulk) UpdateNewValues() *RequestAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestauditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestAuditLogUpsertBulk) Ignore() *RequestAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditLogUpsertBulk) DoNothing() *RequestAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *RequestAuditLogUpsertBulk) Update(set func(*RequestAuditLogUpsert)) *RequestAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestAuditLogUpsertBulk) SetRequestID(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateRequestID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestAuditLogUpsertBulk) ClearRequestID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestAuditLogUpsertBulk) SetUserID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RequestAuditLogUpsertBulk) AddUserID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateUserID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestAuditLogUpsertBulk) SetAPIKeyID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestAuditLogUpsertBulk) AddAPIKeyID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateAPIKeyID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestAuditLogUpsertBulk) SetAccountID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestAuditLogUpsertBulk) AddAccountID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateAccountID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestAuditLogUpsertBulk) ClearAccountID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestAuditLogUpsertBulk) SetGroupID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestAuditLogUpsertBulk) AddGroupID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateGroupID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestAuditLogUpsertBulk) ClearGroupID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *RequestAuditLogUpsertBulk) SetPlatform(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdatePlatform() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdatePlatform()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestAuditLogUpsertBulk) SetEndpoint(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateEndpoint() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *RequestAuditLogUpsertBulk) ClearEndpoint() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *RequestAuditLogUpsertBulk) SetModel(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateModel() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *RequestAuditLogUpsertBulk) ClearModel() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearModel()
	})
}

// SetStream sets the "stream" field.
func (u *RequestAuditLogUpsertBulk) SetStream(v bool) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateStream() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestAuditLogUpsertBulk) SetStatusCode(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestAuditLogUpsertBulk) AddStatusCode(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateStatusCode() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestAuditLogUpsertBulk) ClearStatusCode() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestAuditLogUpsertBulk) SetDurationMs(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestAuditLogUpsertBulk) AddDurationMs(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateDurationMs() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestAuditLogUpsertBulk) ClearDurationMs() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestAuditLogUpsertBulk) SetRequestBody(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateRequestBody() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestAuditLogUpsertBulk) ClearRequestBody() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearRequestBody()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestAuditLogUpsertBulk) SetResponseBody(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateResponseBody() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestAuditLogUpsertBulk) ClearResponseBody() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearResponseBody()
	})
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestAuditLogUpsertBulk) SetRequestBodyTruncated(v bool) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBodyTruncated(v)
	})
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateRequestBodyTruncated() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBodyTruncated()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestAuditLogUpsertBulk) SetResponseBodyTruncated(v bool) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateResponseBodyTruncated() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestAuditLogUpsertBulk) SetRequestBodyBytes(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetRequestBodyBytes(v)
	})
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestAuditLogUpsertBulk) AddRequestBodyBytes(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddRequestBodyBytes(v)
	})
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateRequestBodyBytes() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateRequestBodyBytes()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestAuditLogUpsertBulk) SetResponseBodyBytes(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestAuditLogUpsertBulk) AddResponseBodyBytes(v int) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateResponseBodyBytes() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// SetIsMocked sets the "is_mocked" field.
func (u *RequestAuditLogUpsertBulk) SetIsMocked(v bool) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetIsMocked(v)
	})
}

// UpdateIsMocked sets the "is_mocked" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateIsMocked() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateIsMocked()
	})
}

// SetMockRuleID sets the "mock_rule_id" field.
func (u *RequestAuditLogUpsertBulk) SetMockRuleID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetMockRuleID(v)
	})
}

// AddMockRuleID adds v to the "mock_rule_id" field.
func (u *RequestAuditLogUpsertBulk) AddMockRuleID(v int64) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.AddMockRuleID(v)
	})
}

// UpdateMockRuleID sets the "mock_rule_id" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateMockRuleID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateMockRuleID()
	})
}

// ClearMockRuleID clears the value of the "mock_rule_id" field.
func (u *RequestAuditLogUpsertBulk) ClearMockRuleID() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearMockRuleID()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestAuditLogUpsertBulk) SetErrorMessage(v string) *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestAuditLogUpsertBulk) UpdateErrorMessage() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestAuditLogUpsertBulk) ClearErrorMessage() *RequestAuditLogUpsertBulk {
	return u.Update(func(s *RequestAuditLogUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *RequestAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
