// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/requestauditlog"
)

// RequestAuditLog is the model entity for the RequestAuditLog schema.
type RequestAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint *string `json:"endpoint,omitempty"`
	// Model holds the value of the "model" field.
	Model *string `json:"model,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int `json:"duration_ms,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody *string `json:"request_body,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody *string `json:"response_body,omitempty"`
	// RequestBodyTruncated holds the value of the "request_body_truncated" field.
	RequestBodyTruncated bool `json:"request_body_truncated,omitempty"`
	// ResponseBodyTruncated holds the value of the "response_body_truncated" field.
	ResponseBodyTruncated bool `json:"response_body_truncated,omitempty"`
	// RequestBodyBytes holds the value of the "request_body_bytes" field.
	RequestBodyBytes int `json:"request_body_bytes,omitempty"`
	// ResponseBodyBytes holds the value of the "response_body_bytes" field.
	ResponseBodyBytes int `json:"response_body_bytes,omitempty"`
	// IsMocked holds the value of the "is_mocked" field.
	IsMocked bool `json:"is_mocked,omitempty"`
	// MockRuleID holds the value of the "mock_rule_id" field.
	MockRuleID *int64 `json:"mock_rule_id,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestauditlog.FieldStream, requestauditlog.FieldRequestBodyTruncated, requestauditlog.FieldResponseBodyTruncated, requestauditlog.FieldIsMocked:
			values[i] = new(sql.NullBool)
		case requestauditlog.FieldID, requestauditlog.FieldUserID, requestauditlog.FieldAPIKeyID, requestauditlog.FieldAccountID, requestauditlog.FieldGroupID, requestauditlog.FieldStatusCode, requestauditlog.FieldDurationMs, requestauditlog.FieldRequestBodyBytes, requestauditlog.FieldResponseBodyBytes, requestauditlog.FieldMockRuleID:
			values[i] = new(sql.NullInt64)
		case requestauditlog.FieldRequestID, requestauditlog.FieldPlatform, requestauditlog.FieldEndpoint, requestauditlog.FieldModel, requestauditlog.FieldRequestBody, requestauditlog.FieldResponseBody, requestauditlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case requestauditlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestAuditLog fields.
func (_m *RequestAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestauditlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case requestauditlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case requestauditlog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case requestauditlog.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case requestauditlog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case requestauditlog.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case requestauditlog.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = new(string)
				*_m.Endpoint = value.String
			}
		case requestauditlog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case requestauditlog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case requestauditlog.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case requestauditlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case requestauditlog.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = new(string)
				*_m.RequestBody = value.String
			}
		case requestauditlog.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = new(string)
				*_m.ResponseBody = value.String
			}
		case requestauditlog.FieldRequestBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_truncated", values[i])
			} else if value.Valid {
				_m.RequestBodyTruncated = value.Bool
			}
		case requestauditlog.FieldResponseBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_truncated", values[i])
			} else if value.Valid {
				_m.ResponseBodyTruncated = value.Bool
			}
		case requestauditlog.FieldRequestBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_bytes", values[i])
			} else if value.Valid {
				_m.RequestBodyBytes = int(value.Int64)
			}
		case requestauditlog.FieldResponseBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_bytes", values[i])
			} else if value.Valid {
				_m.ResponseBodyBytes = int(value.Int64)
			}
		case requestauditlog.FieldIsMocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_mocked", values[i])
			} else if value.Valid {
				_m.IsMocked = value.Bool
			}
		case requestauditlog.FieldMockRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mock_rule_id", values[i])
			} else if value.Valid {
				_m.MockRuleID = new(int64)
				*_m.MockRuleID = value.Int64
			}
		case requestauditlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case requestauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *RequestAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestAuditLog.
// Note that you need to call RequestAuditLog.Unwrap() before calling this method if this RequestAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestAuditLog) Update() *RequestAuditLogUpdateOne {
	return NewRequestAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestAuditLog) Unwrap() *RequestAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("RequestAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.Endpoint; v != nil {
		builder.WriteString("endpoint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestBody; v != nil {
		builder.WriteString("request_body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponseBody; v != nil {
		builder.WriteString("response_body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("response_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("request_body_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBodyBytes))
	builder.WriteString(", ")
	builder.WriteString("response_body_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodyBytes))
	builder.WriteString(", ")
	builder.WriteString("is_mocked=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMocked))
	builder.WriteString(", ")
	if v := _m.MockRuleID; v != nil {
		builder.WriteString("mock_rule_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestAuditLogs is a parsable slice of RequestAuditLog.
type RequestAuditLogs []*RequestAuditLog
