// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestauditlog"
)

// RequestAuditLogUpdate is the builder for updating RequestAuditLog entities.
type RequestAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestAuditLogMutation
}

// Where appends a list predicates to the RequestAuditLogUpdate builder.
func (_u *RequestAuditLogUpdate) Where(ps ...predicate.RequestAuditLog) *RequestAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestAuditLogUpdate) SetRequestID(v string) *RequestAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableRequestID(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestAuditLogUpdate) ClearRequestID() *RequestAuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestAuditLogUpdate) SetUserID(v int64) *RequestAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableUserID(v *int64) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RequestAuditLogUpdate) AddUserID(v int64) *RequestAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestAuditLogUpdate) SetAPIKeyID(v int64) *RequestAuditLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableAPIKeyID(v *int64) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RequestAuditLogUpdate) AddAPIKeyID(v int64) *RequestAuditLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestAuditLogUpdate) SetAccountID(v int64) *RequestAuditLogUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableAccountID(v *int64) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *RequestAuditLogUpdate) AddAccountID(v int64) *RequestAuditLogUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *RequestAuditLogUpdate) ClearAccountID() *RequestAuditLogUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestAuditLogUpdate) SetGroupID(v int64) *RequestAuditLogUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableGroupID(v *int64) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RequestAuditLogUpdate) AddGroupID(v int64) *RequestAuditLogUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestAuditLogUpdate) ClearGroupID() *RequestAuditLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RequestAuditLogUpdate) SetPlatform(v string) *RequestAuditLogUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillablePlatform(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *RequestAuditLogUpdate) SetEndpoint(v string) *RequestAuditLogUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableEndpoint(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *RequestAuditLogUpdate) ClearEndpoint() *RequestAuditLogUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestAuditLogUpdate) SetModel(v string) *RequestAuditLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableModel(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *RequestAuditLogUpdate) ClearModel() *RequestAuditLogUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestAuditLogUpdate) SetStream(v bool) *RequestAuditLogUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableStream(v *bool) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestAuditLogUpdate) SetStatusCode(v int) *RequestAuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableStatusCode(v *int) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestAuditLogUpdate) AddStatusCode(v int) *RequestAuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *RequestAuditLogUpdate) ClearStatusCode() *RequestAuditLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestAuditLogUpdate) SetDurationMs(v int) *RequestAuditLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableDurationMs(v *int) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestAuditLogUpdate) AddDurationMs(v int) *RequestAuditLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestAuditLogUpdate) ClearDurationMs() *RequestAuditLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestAuditLogUpdate) SetRequestBody(v string) *RequestAuditLogUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableRequestBody(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RequestAuditLogUpdate) ClearRequestBody() *RequestAuditLogUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestAuditLogUpdate) SetResponseBody(v string) *RequestAuditLogUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableResponseBody(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestAuditLogUpdate) ClearResponseBody() *RequestAuditLogUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_u *RequestAuditLogUpdate) SetRequestBodyTruncated(v bool) *RequestAuditLogUpdate {
	_u.mutation.SetRequestBodyTruncated(v)
	return _u
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableRequestBodyTruncated(v *bool) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetRequestBodyTruncated(*v)
	}
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *RequestAuditLogUpdate) SetResponseBodyTruncated(v bool) *RequestAuditLogUpdate {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableResponseBodyTruncated(v *bool) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_u *RequestAuditLogUpdate) SetRequestBodyBytes(v int) *RequestAuditLogUpdate {
	_u.mutation.ResetRequestBodyBytes()
	_u.mutation.SetRequestBodyBytes(v)
	return _u
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableRequestBodyBytes(v *int) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetRequestBodyBytes(*v)
	}
	return _u
}

// AddRequestBodyBytes adds value to the "request_body_bytes" field.
func (_u *RequestAuditLogUpdate) AddRequestBodyBytes(v int) *RequestAuditLogUpdate {
	_u.mutation.AddRequestBodyBytes(v)
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *RequestAuditLogUpdate) SetResponseBodyBytes(v int) *RequestAuditLogUpdate {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableResponseBodyBytes(v *int) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *RequestAuditLogUpdate) AddResponseBodyBytes(v int) *RequestAuditLogUpdate {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// SetIsMocked sets the "is_mocked" field.
func (_u *RequestAuditLogUpdate) SetIsMocked(v bool) *RequestAuditLogUpdate {
	_u.mutation.SetIsMocked(v)
	return _u
}

// SetNillableIsMocked sets the "is_mocked" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableIsMocked(v *bool) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetIsMocked(*v)
	}
	return _u
}

// SetMockRuleID sets the "mock_rule_id" field.
func (_u *RequestAuditLogUpdate) SetMockRuleID(v int64) *RequestAuditLogUpdate {
	_u.mutation.ResetMockRuleID()
	_u.mutation.SetMockRuleID(v)
	return _u
}

// SetNillableMockRuleID sets the "mock_rule_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableMockRuleID(v *int64) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetMockRuleID(*v)
	}
	return _u
}

// AddMockRuleID adds value to the "mock_rule_id" field.
func (_u *RequestAuditLogUpdate) AddMockRuleID(v int64) *RequestAuditLogUpdate {
	_u.mutation.AddMockRuleID(v)
	return _u
}

// ClearMockRuleID clears the value of the "mock_rule_id" field.
func (_u *RequestAuditLogUpdate) ClearMockRuleID() *RequestAuditLogUpdate {
	_u.mutation.ClearMockRuleID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestAuditLogUpdate) SetErrorMessage(v string) *RequestAuditLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestAuditLogUpdate) SetNillableErrorMessage(v *string) *RequestAuditLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestAuditLogUpdate) ClearErrorMessage() *RequestAuditLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the RequestAuditLogMutation object of the builder.
func (_u *RequestAuditLogUpdate) Mutation() *RequestAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditLogUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := requestauditlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := requestauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := requestauditlog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestauditlog.Table, requestauditlog.Columns, sqlgraph.NewFieldSpec(requestauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(requestauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(requestauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(requestauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(requestauditlog.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(requestauditlog.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(requestauditlog.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(requestauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(requestauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(requestauditlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(requestauditlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(requestauditlog.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(requestauditlog.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestauditlog.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(requestauditlog.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestauditlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(requestauditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestauditlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(requestauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestauditlog.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestauditlog.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestBodyBytes(); ok {
		_spec.AddField(requestauditlog.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(requestauditlog.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsMocked(); ok {
		_spec.SetField(requestauditlog.FieldIsMocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MockRuleID(); ok {
		_spec.SetField(requestauditlog.FieldMockRuleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMockRuleID(); ok {
		_spec.AddField(requestauditlog.FieldMockRuleID, field.TypeInt64, value)
	}
	if _u.mutation.MockRuleIDCleared() {
		_spec.ClearField(requestauditlog.FieldMockRuleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestauditlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestauditlog.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestAuditLogUpdateOne is the builder for updating a single RequestAuditLog entity.
type RequestAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestAuditLogMutation
}

// SetRequestID sets the "request_id" field.
func (_u *RequestAuditLogUpdateOne) SetRequestID(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableRequestID(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestAuditLogUpdateOne) ClearRequestID() *RequestAuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestAuditLogUpdateOne) SetUserID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableUserID(v *int64) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RequestAuditLogUpdateOne) AddUserID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestAuditLogUpdateOne) SetAPIKeyID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableAPIKeyID(v *int64) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RequestAuditLogUpdateOne) AddAPIKeyID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestAuditLogUpdateOne) SetAccountID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableAccountID(v *int64) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *RequestAuditLogUpdateOne) AddAccountID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *RequestAuditLogUpdateOne) ClearAccountID() *RequestAuditLogUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestAuditLogUpdateOne) SetGroupID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableGroupID(v *int64) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RequestAuditLogUpdateOne) AddGroupID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestAuditLogUpdateOne) ClearGroupID() *RequestAuditLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RequestAuditLogUpdateOne) SetPlatform(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillablePlatform(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *RequestAuditLogUpdateOne) SetEndpoint(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableEndpoint(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *RequestAuditLogUpdateOne) ClearEndpoint() *RequestAuditLogUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestAuditLogUpdateOne) SetModel(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableModel(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *RequestAuditLogUpdateOne) ClearModel() *RequestAuditLogUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestAuditLogUpdateOne) SetStream(v bool) *RequestAuditLogUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableStream(v *bool) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestAuditLogUpdateOne) SetStatusCode(v int) *RequestAuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableStatusCode(v *int) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestAuditLogUpdateOne) AddStatusCode(v int) *RequestAuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *RequestAuditLogUpdateOne) ClearStatusCode() *RequestAuditLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestAuditLogUpdateOne) SetDurationMs(v int) *RequestAuditLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableDurationMs(v *int) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestAuditLogUpdateOne) AddDurationMs(v int) *RequestAuditLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestAuditLogUpdateOne) ClearDurationMs() *RequestAuditLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestAuditLogUpdateOne) SetRequestBody(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableRequestBody(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RequestAuditLogUpdateOne) ClearRequestBody() *RequestAuditLogUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestAuditLogUpdateOne) SetResponseBody(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableResponseBody(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestAuditLogUpdateOne) ClearResponseBody() *RequestAuditLogUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_u *RequestAuditLogUpdateOne) SetRequestBodyTruncated(v bool) *RequestAuditLogUpdateOne {
	_u.mutation.SetRequestBodyTruncated(v)
	return _u
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableRequestBodyTruncated(v *bool) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestBodyTruncated(*v)
	}
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *RequestAuditLogUpdateOne) SetResponseBodyTruncated(v bool) *RequestAuditLogUpdateOne {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableResponseBodyTruncated(v *bool) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_u *RequestAuditLogUpdateOne) SetRequestBodyBytes(v int) *RequestAuditLogUpdateOne {
	_u.mutation.ResetRequestBodyBytes()
	_u.mutation.SetRequestBodyBytes(v)
	return _u
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableRequestBodyBytes(v *int) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestBodyBytes(*v)
	}
	return _u
}

// AddRequestBodyBytes adds value to the "request_body_bytes" field.
func (_u *RequestAuditLogUpdateOne) AddRequestBodyBytes(v int) *RequestAuditLogUpdateOne {
	_u.mutation.AddRequestBodyBytes(v)
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *RequestAuditLogUpdateOne) SetResponseBodyBytes(v int) *RequestAuditLogUpdateOne {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableResponseBodyBytes(v *int) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *RequestAuditLogUpdateOne) AddResponseBodyBytes(v int) *RequestAuditLogUpdateOne {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// SetIsMocked sets the "is_mocked" field.
func (_u *RequestAuditLogUpdateOne) SetIsMocked(v bool) *RequestAuditLogUpdateOne {
	_u.mutation.SetIsMocked(v)
	return _u
}

// SetNillableIsMocked sets the "is_mocked" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableIsMocked(v *bool) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetIsMocked(*v)
	}
	return _u
}

// SetMockRuleID sets the "mock_rule_id" field.
func (_u *RequestAuditLogUpdateOne) SetMockRuleID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.ResetMockRuleID()
	_u.mutation.SetMockRuleID(v)
	return _u
}

// SetNillableMockRuleID sets the "mock_rule_id" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableMockRuleID(v *int64) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetMockRuleID(*v)
	}
	return _u
}

// AddMockRuleID adds value to the "mock_rule_id" field.
func (_u *RequestAuditLogUpdateOne) AddMockRuleID(v int64) *RequestAuditLogUpdateOne {
	_u.mutation.AddMockRuleID(v)
	return _u
}

// ClearMockRuleID clears the value of the "mock_rule_id" field.
func (_u *RequestAuditLogUpdateOne) ClearMockRuleID() *RequestAuditLogUpdateOne {
	_u.mutation.ClearMockRuleID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestAuditLogUpdateOne) SetErrorMessage(v string) *RequestAuditLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestAuditLogUpdateOne) SetNillableErrorMessage(v *string) *RequestAuditLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestAuditLogUpdateOne) ClearErrorMessage() *RequestAuditLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the RequestAuditLogMutation object of the builder.
func (_u *RequestAuditLogUpdateOne) Mutation() *RequestAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestAuditLogUpdate builder.
func (_u *RequestAuditLogUpdateOne) Where(ps ...predicate.RequestAuditLog) *RequestAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestAuditLogUpdateOne) Select(field string, fields ...string) *RequestAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestAuditLog entity.
func (_u *RequestAuditLogUpdateOne) Save(ctx context.Context) (*RequestAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditLogUpdateOne) SaveX(ctx context.Context) *RequestAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := requestauditlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := requestauditlog.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := requestauditlog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "RequestAuditLog.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestauditlog.Table, requestauditlog.Columns, sqlgraph.NewFieldSpec(requestauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestauditlog.FieldID)
		for _, f := range fields {
			if !requestauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(requestauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(requestauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(requestauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(requestauditlog.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(requestauditlog.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(requestauditlog.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(requestauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(requestauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(requestauditlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(requestauditlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(requestauditlog.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(requestauditlog.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestauditlog.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(requestauditlog.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestauditlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestauditlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(requestauditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestauditlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestauditlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(requestauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestauditlog.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestauditlog.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestBodyBytes(); ok {
		_spec.AddField(requestauditlog.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestauditlog.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(requestauditlog.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsMocked(); ok {
		_spec.SetField(requestauditlog.FieldIsMocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MockRuleID(); ok {
		_spec.SetField(requestauditlog.FieldMockRuleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMockRuleID(); ok {
		_spec.AddField(requestauditlog.FieldMockRuleID, field.TypeInt64, value)
	}
	if _u.mutation.MockRuleIDCleared() {
		_spec.ClearField(requestauditlog.FieldMockRuleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestauditlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestauditlog.FieldErrorMessage, field.TypeString)
	}
	_node = &RequestAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
