// Code generated by ent, DO NOT EDIT.

package requestauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requestauditlog type in the database.
	Label = "request_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldRequestBodyTruncated holds the string denoting the request_body_truncated field in the database.
	FieldRequestBodyTruncated = "request_body_truncated"
	// FieldResponseBodyTruncated holds the string denoting the response_body_truncated field in the database.
	FieldResponseBodyTruncated = "response_body_truncated"
	// FieldRequestBodyBytes holds the string denoting the request_body_bytes field in the database.
	FieldRequestBodyBytes = "request_body_bytes"
	// FieldResponseBodyBytes holds the string denoting the response_body_bytes field in the database.
	FieldResponseBodyBytes = "response_body_bytes"
	// FieldIsMocked holds the string denoting the is_mocked field in the database.
	FieldIsMocked = "is_mocked"
	// FieldMockRuleID holds the string denoting the mock_rule_id field in the database.
	FieldMockRuleID = "mock_rule_id"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the requestauditlog in the database.
	Table = "request_audit_logs"
)

// Columns holds all SQL columns for requestauditlog fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldPlatform,
	FieldEndpoint,
	FieldModel,
	FieldStream,
	FieldStatusCode,
	FieldDurationMs,
	FieldRequestBody,
	FieldResponseBody,
	FieldRequestBodyTruncated,
	FieldResponseBodyTruncated,
	FieldRequestBodyBytes,
	FieldResponseBodyBytes,
	FieldIsMocked,
	FieldMockRuleID,
	FieldErrorMessage,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultRequestBodyTruncated holds the default value on creation for the "request_body_truncated" field.
	DefaultRequestBodyTruncated bool
	// DefaultResponseBodyTruncated holds the default value on creation for the "response_body_truncated" field.
	DefaultResponseBodyTruncated bool
	// DefaultRequestBodyBytes holds the default value on creation for the "request_body_bytes" field.
	DefaultRequestBodyBytes int
	// DefaultResponseBodyBytes holds the default value on creation for the "response_body_bytes" field.
	DefaultResponseBodyBytes int
	// DefaultIsMocked holds the default value on creation for the "is_mocked" field.
	DefaultIsMocked bool
	// ErrorMessageValidator is a validator for the "error_message" field. It is called by the builders before save.
	ErrorMessageValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RequestAuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByRequestBody orders the results by the request_body field.
func ByRequestBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBody, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByRequestBodyTruncated orders the results by the request_body_truncated field.
func ByRequestBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyTruncated, opts...).ToFunc()
}

// ByResponseBodyTruncated orders the results by the response_body_truncated field.
func ByResponseBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyTruncated, opts...).ToFunc()
}

// ByRequestBodyBytes orders the results by the request_body_bytes field.
func ByRequestBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyBytes, opts...).ToFunc()
}

// ByResponseBodyBytes orders the results by the response_body_bytes field.
func ByResponseBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyBytes, opts...).ToFunc()
}

// ByIsMocked orders the results by the is_mocked field.
func ByIsMocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsMocked, opts...).ToFunc()
}

// ByMockRuleID orders the results by the mock_rule_id field.
func ByMockRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMockRuleID, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
