// Code generated by ent, DO NOT EDIT.

package requestauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldGroupID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldPlatform, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldEndpoint, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldModel, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldStream, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldDurationMs, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBody, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBody, v))
}

// RequestBodyTruncated applies equality check predicate on the "request_body_truncated" field. It's identical to RequestBodyTruncatedEQ.
func RequestBodyTruncated(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBodyTruncated, v))
}

// ResponseBodyTruncated applies equality check predicate on the "response_body_truncated" field. It's identical to ResponseBodyTruncatedEQ.
func ResponseBodyTruncated(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// RequestBodyBytes applies equality check predicate on the "request_body_bytes" field. It's identical to RequestBodyBytesEQ.
func RequestBodyBytes(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBodyBytes, v))
}

// ResponseBodyBytes applies equality check predicate on the "response_body_bytes" field. It's identical to ResponseBodyBytesEQ.
func ResponseBodyBytes(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// IsMocked applies equality check predicate on the "is_mocked" field. It's identical to IsMockedEQ.
func IsMocked(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldIsMocked, v))
}

// MockRuleID applies equality check predicate on the "mock_rule_id" field. It's identical to MockRuleIDEQ.
func MockRuleID(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldMockRuleID, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldAPIKeyID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldAccountID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldGroupID))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldPlatform, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointIsNil applies the IsNil predicate on the "endpoint" field.
func EndpointIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldEndpoint))
}

// EndpointNotNil applies the NotNil predicate on the "endpoint" field.
func EndpointNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldEndpoint))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldModel, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldStream, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldStatusCode))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldDurationMs))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldRequestBody, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldResponseBody, v))
}

// RequestBodyTruncatedEQ applies the EQ predicate on the "request_body_truncated" field.
func RequestBodyTruncatedEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBodyTruncated, v))
}

// RequestBodyTruncatedNEQ applies the NEQ predicate on the "request_body_truncated" field.
func RequestBodyTruncatedNEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldRequestBodyTruncated, v))
}

// ResponseBodyTruncatedEQ applies the EQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// ResponseBodyTruncatedNEQ applies the NEQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedNEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldResponseBodyTruncated, v))
}

// RequestBodyBytesEQ applies the EQ predicate on the "request_body_bytes" field.
func RequestBodyBytesEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldRequestBodyBytes, v))
}

// RequestBodyBytesNEQ applies the NEQ predicate on the "request_body_bytes" field.
func RequestBodyBytesNEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldRequestBodyBytes, v))
}

// RequestBodyBytesIn applies the In predicate on the "request_body_bytes" field.
func RequestBodyBytesIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldRequestBodyBytes, vs...))
}

// RequestBodyBytesNotIn applies the NotIn predicate on the "request_body_bytes" field.
func RequestBodyBytesNotIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldRequestBodyBytes, vs...))
}

// RequestBodyBytesGT applies the GT predicate on the "request_body_bytes" field.
func RequestBodyBytesGT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldRequestBodyBytes, v))
}

// RequestBodyBytesGTE applies the GTE predicate on the "request_body_bytes" field.
func RequestBodyBytesGTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldRequestBodyBytes, v))
}

// RequestBodyBytesLT applies the LT predicate on the "request_body_bytes" field.
func RequestBodyBytesLT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldRequestBodyBytes, v))
}

// RequestBodyBytesLTE applies the LTE predicate on the "request_body_bytes" field.
func RequestBodyBytesLTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldRequestBodyBytes, v))
}

// ResponseBodyBytesEQ applies the EQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesNEQ applies the NEQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesNEQ(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesIn applies the In predicate on the "response_body_bytes" field.
func ResponseBodyBytesIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesNotIn applies the NotIn predicate on the "response_body_bytes" field.
func ResponseBodyBytesNotIn(vs ...int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesGT applies the GT predicate on the "response_body_bytes" field.
func ResponseBodyBytesGT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesGTE applies the GTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesGTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLT applies the LT predicate on the "response_body_bytes" field.
func ResponseBodyBytesLT(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLTE applies the LTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesLTE(v int) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldResponseBodyBytes, v))
}

// IsMockedEQ applies the EQ predicate on the "is_mocked" field.
func IsMockedEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldIsMocked, v))
}

// IsMockedNEQ applies the NEQ predicate on the "is_mocked" field.
func IsMockedNEQ(v bool) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldIsMocked, v))
}

// MockRuleIDEQ applies the EQ predicate on the "mock_rule_id" field.
func MockRuleIDEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldMockRuleID, v))
}

// MockRuleIDNEQ applies the NEQ predicate on the "mock_rule_id" field.
func MockRuleIDNEQ(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldMockRuleID, v))
}

// MockRuleIDIn applies the In predicate on the "mock_rule_id" field.
func MockRuleIDIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldMockRuleID, vs...))
}

// MockRuleIDNotIn applies the NotIn predicate on the "mock_rule_id" field.
func MockRuleIDNotIn(vs ...int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldMockRuleID, vs...))
}

// MockRuleIDGT applies the GT predicate on the "mock_rule_id" field.
func MockRuleIDGT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldMockRuleID, v))
}

// MockRuleIDGTE applies the GTE predicate on the "mock_rule_id" field.
func MockRuleIDGTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldMockRuleID, v))
}

// MockRuleIDLT applies the LT predicate on the "mock_rule_id" field.
func MockRuleIDLT(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldMockRuleID, v))
}

// MockRuleIDLTE applies the LTE predicate on the "mock_rule_id" field.
func MockRuleIDLTE(v int64) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldMockRuleID, v))
}

// MockRuleIDIsNil applies the IsNil predicate on the "mock_rule_id" field.
func MockRuleIDIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldMockRuleID))
}

// MockRuleIDNotNil applies the NotNil predicate on the "mock_rule_id" field.
func MockRuleIDNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldMockRuleID))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestAuditLog) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestAuditLog) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestAuditLog) predicate.RequestAuditLog {
	return predicate.RequestAuditLog(sql.NotPredicates(p))
}
